---
- name: fetch rados.py
  get_url: url={{ ceph.rados_url }}
           dest="{{ openstack_source.virtualenv_base }}/glance/lib/python2.7/site-packages/rados.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'source'

- name: fetch rbd.py
  get_url: url={{ ceph.rbd_url }}
           dest="{{ openstack_source.virtualenv_base }}/glance/lib/python2.7/site-packages/rbd.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'source'

- name: fetch rados.py
  get_url: url={{ ceph.rados_url }}
           dest="{{ lookup('items', 'openstack_package.virtualenv_base') }}/glance/lib/python2.7/site-packages/rados.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'package'

- name: fetch rbd.py
  get_url: url={{ ceph.rbd_url }}
           dest="{{ lookup('items', 'openstack_package.virtualenv_base') }}/glance/lib/python2.7/site-packages/rbd.py"
           owner=root
           group=root
           mode=0644
  when: openstack_install_method == 'package'

- name: fetch glance keyring
  slurp: path=/etc/ceph/ceph.client.glance.keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: glance_keyring

- name: write glance keyring
  copy:
    dest: "{{ glance_keyring['source'] }}"
    content: "{{ glance_keyring['content'] | b64decode }}"
    mode: 0644
    owner: glance
    group: glance
