---
dependencies:
  - role: ensure-pip
    tags: ['prereboot']
  - role: endpoints
  - role: apt-repos
    tags: ['prereboot']
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.hwraid.repo }} precise main'
        key_url: '{{ apt_repos.hwraid.key_url }}'
    when: common.hwraid.enabled|bool
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.sensu.repo }} {{ apt_repos.sensu.distribution }} {{ apt_repos.sensu.components }}'
        key_url: '{{ apt_repos.sensu.key_url }}'
        validate_certs: no
    when: monitoring.enabled|default(True)|bool
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.ovn.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.ovn.key_url }}'
    when: neutron.plugin == 'ovn'
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.kernel.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.kernel.key_url }}'
    when: apt_repos.kernel is defined
    tags: ['kernel']
  - role: docker
    when: docker.enabled is defined and docker.enabled|bool
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: common
    logdata: "{{ common.logs }}"
