---
- name: neutron process check
  sensu_process_check: service=neutron-server
  notify: restart sensu-client

- name: neutron free fips check
  sensu_check: name=check-neutron-free-fips plugin=check-neutron-fip.sh state=absent
  notify: restart sensu-client

- name: neutron free fips metrics check
  sensu_metrics_check: name=neutron-free-fips-metric plugin=check-neutron-fip.sh state=absent
  notify: restart sensu-client

- name: neutron metrics
  template: src=etc/collectd/plugins/neutron.conf dest=/etc/collectd/plugins/neutron.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd

- name: neutron sla metrics
  sensu_metrics_check: name=neutron-sla-metrics plugin=metrics-os-api.py
                       args='-S neutron --scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client

- name: lbaas sla metrics
  sensu_metrics_check: name=lbaas-sla-metrics plugin=metrics-os-api.py
                       args='-S lbaas --scheme {{ monitoring.graphite.host_prefix }}'
  when: (neutron.lbaas.enabled == "smart" and
        groups['controller'][0] not in groups['compute']) or
        neutron.lbaas.enabled|bool
  notify: restart sensu-client

- name: neutron-server cpu and memory metrics
  sensu_metrics_check:
    name: neutron-server-usage-metrics
    plugin: metrics-process-usage.py
    use_sudo: true
    args: >
      -n neutron-server
      -w {{ cpu_warn_pct }}
      -c {{ cpu_crit_pct }}
      -W {{ mem_warn_pct }}
      -C {{ mem_crit_pct }}
      --scheme {{ monitoring.graphite.host_prefix }}
  notify: restart sensu-client

- name: neutron-server tx/rx queue metrics
  sensu_metrics_check:
    name: neutron-server-queue-metrics
    plugin: metrics-network-queues.py
    use_sudo: true
    args: >
      -n neutron-server
      --scheme {{ monitoring.graphite.host_prefix }}
  notify: restart sensu-client
