- name: restart openvswitch-switch
  service: name=openvswitch-switch state=restarted args="--save-flows=yes"

- name: restart vtep-ovsdb
  service: name=vtep-ovsdb state=restarted

- name: restart ovn-controller-vtep
  service: name=ovn-controller-vtep state=restarted
