---
- name: discover keystone setup status
  command: mysql --batch --silent keystone -e "select type from service where type = 'compute'"
  failed_when: false
  register: keystone_setup

- name: set keystone_configured fact
  set_fact: keystone_configured=True
  when: keystone_setup.stdout|search("compute")

- name: bootstrap with old admin token
  include: admin_token.yml
  when: not keystone.use_keystone_bootstrap|bool

- name: keystone bootstrap user
  command: keystone-manage bootstrap
  environment:
    OS_BOOTSTRAP_USERNAME: "{{ keystone.bootstrap.user }}"
    OS_BOOTSTRAP_PASSWORD: "{{ keystone.bootstrap.password }}"
    OS_BOOTSTRAP_PROJECT_NAME: "{{ keystone.bootstrap.project }}"
    OS_BOOTSTRAP_ROLE_NAME: "{{ keystone.bootstrap.role }}"
    OS_BOOTSTRAP_ADMIN_URL: "{{ endpoints.keystone.url.admin }}/v2.0"
    OS_BOOTSTRAP_INTERNAL_URL: "{{ endpoints.keystone.url.internal }}/v2.0"
    OS_BOOTSTRAP_PUBLIC_URL: "{{ endpoints.keystone.url.public }}/v2.0"
    OS_BOOTSTRAP_SERVICE_NAME: "{{ 'keystone' }}"  # otherwise it uses the keystone variable
    OS_BOOTSTRAP_REGION_ID: "RegionOne"
  when: keystone.use_keystone_bootstrap|bool

- name: keystone tenants
  keystone_user: tenant={{ item }}
                 tenant_description="{{ item }} tenant"
                 endpoint=http://127.0.0.1:{{ endpoints.keystone_admin.port.backend_api }}/v2.0
                 login_tenant_name={{ keystone.bootstrap.project }}
                 login_user={{ keystone.bootstrap.user }}
                 login_password={{ secrets.admin_password }}
  with_items: keystone.tenants

- name: keystone users
  keystone_user: user={{ item.name }}
                 password={{ item.password }}
                 tenant={{ item.tenant }}
                 endpoint=http://127.0.0.1:{{ endpoints.keystone_admin.port.backend_api }}/v2.0
                 login_tenant_name={{ keystone.bootstrap.project }}
                 login_user={{ keystone.bootstrap.user }}
                 login_password={{ secrets.admin_password }}
  with_items: keystone.users

- name: keystone roles
  keystone_user: role={{ item.role }}
                 user={{ item.user }}
                 tenant={{ item.tenant }}
                 endpoint=http://127.0.0.1:{{ endpoints.keystone_admin.port.backend_api }}/v2.0
                 login_tenant_name={{ keystone.bootstrap.project }}
                 login_user={{ keystone.bootstrap.user }}
                 login_password={{ secrets.admin_password }}
  with_items: keystone.user_roles

- name: heat stack user
  keystone_user: user=heat_stack_user
                 password={{ secrets.service_password }}
                 tenant=admin
                 endpoint=http://127.0.0.1:{{ endpoints.keystone_admin.port.backend_api }}/v2.0
                 login_tenant_name={{ keystone.bootstrap.project }}
                 login_user={{ keystone.bootstrap.user }}
                 login_password={{ secrets.admin_password }}
  when: heat.enabled|bool

- name: heat stack user role
  keystone_user: role=heat_stack_user
                 user=heat_stack_user
                 tenant=admin
                 endpoint=http://127.0.0.1:{{ endpoints.keystone_admin.port.backend_api }}/v2.0
                 login_tenant_name={{ keystone.bootstrap.project }}
                 login_user={{ keystone.bootstrap.user }}
                 login_password={{ secrets.admin_password }}
  when: heat.enabled|bool
