- name: install dependencies
  apt: pkg={{ item }}
  with_items:
    - openvswitch-common
    - openvswitch-datapath-dkms
    - openvswitch-switch
    - ovn-common
    - ovn-host
    - python-openvswitch

- name: start openvswitch service
  service: name=openvswitch-switch state=started enabled=yes

# Using 'command' instead of the openvswitch_bridge module due to lack of
# support beyond managing bridges. Also using 'changed_when: false' because
# the 'ovs-vsctl set open' command only provides output when it fails.

- name: setup connection to remote database
  command: ovs-vsctl set open . external-ids:ovn-remote=tcp:{{ endpoints.ovndb }}:6640
  changed_when: false

- name: add ovs integration bridge
  command: ovs-vsctl --may-exist add-br br-int

- name: enable integration bridge
  command: ovs-vsctl set open . external-ids:ovn-bridge=br-int
  changed_when: false

- name: configure integration bridge
  command: ovs-vsctl set bridge br-int fail-mode=secure other-config:disable-in-band=true
  changed_when: false

- name: configure overlay network protocol
  command: ovs-vsctl set open . external-ids:ovn-encap-type={{ item }}
  changed_when: false
  with_items: neutron.tunnel_types

- name: configure overlay network endpoint
  command: ovs-vsctl set open . external-ids:ovn-encap-ip={{ hostvars[inventory_hostname][neutron.overlay_interface|default(primary_interface)]['ipv4']['address'] }}
  changed_when: false

- name: add ovs provider network bridges
  command: ovs-vsctl --may-exist add-br {{item.split(':')[1]}}
  with_items: "{{ neutron.bridge_mappings.split(',') }}"

- name: configure ovn bridge mappings
  command: ovs-vsctl set open . external-ids:ovn-bridge-mappings={{ neutron.bridge_mappings }}

- name: start ovn controller
  service: name=ovn-host state=started enabled=yes
