- name: install sensu
  apt: name=sensu state=present

- name: copy sensu configs
  template: src=sensu-conf/{{ item }} dest=/etc/sensu/conf.d/{{ item }}
  with_items:
    - transport.json
    - rabbitmq.json
    - redis.json

- name: update defaults
  shell: update-rc.d {{ item }} defaults
  with_items:
    - sensu-server

- name: restart sensu services
  service: name={{ item }}  state=restarted
  with_items:
    - sensu-server

