- name: install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - openvswitch-common
    - openvswitch-switch
    - ovn-common
    - ovn-central
    - python-openvswitch
  notify:
    - stop openvswitch-switch
    - restart ovn-central

- name: remove openvswitch-switch from startup
  shell: update-rc.d -f openvswitch-switch remove
  sudo: true

- name: check if ovn northbound database exists
  stat: path="{{ovs_db_dir}}/ovnnb.db"
  register: ovnnb

- name: check if ovn southbound database exists
  stat: path="{{ovs_db_dir}}/ovnsb.db"
  register: ovnsb

- name: create ovn northbound database
  shell: ovsdb-tool create {{ovs_db_dir}}/ovnnb.db {{ ovs_db_nb_schema }}
  when: not ovnnb.stat.exists

- name: create ovn southbound database
  shell: ovsdb-tool create {{ovs_db_dir}}/ovnsb.db {{ ovs_db_sb_schema }}
  when: not ovnsb.stat.exists

- name: permit access to ovn databases
  ufw: rule=allow to_port={{ item }} proto=tcp
  with_items:
    - "{{ endpoints.ovndb.port.northbound }}"
    - "{{ endpoints.ovndb.port.southbound }}"
  tags: ufw

- name: start ovn northd service
  service: name=ovn-central state=started enabled=yes

- include: monitoring.yml tags=monitoring,common
  when: monitoring.enabled|default('True')|bool
