- name: install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - ucarp
    - openvswitch-common
    - openvswitch-switch
    - ovn-common
    - ovn-central
    - python-openvswitch
  notify:
    - stop openvswitch-switch

- name: bounce network interfaces
  shell: ifdown -a ; ifup -a

- name: remove openvswitch-switch from startup
  shell: update-rc.d -f openvswitch-switch remove
  sudo: true

- name: check if ovn northbound database exists
  stat: path="{{ovs_db_dir}}/ovnnb.db"
  register: ovnnb

- name: check if ovn southbound database exists
  stat: path="{{ovs_db_dir}}/ovnsb.db"
  register: ovnsb

- name: create ovn northbound database
  shell: ovsdb-tool create {{ovs_db_dir}}/ovnnb.db {{ ovs_db_nb_schema }}
  when: not ovnnb.stat.exists

- name: create ovn southbound database
  shell: ovsdb-tool create {{ovs_db_dir}}/ovnsb.db {{ ovs_db_sb_schema }}
  when: not ovnsb.stat.exists

- name: permit access to ovn databases
  ufw: rule=allow to_port={{ item }} proto=tcp
  with_items:
    - "{{ endpoints.ovnnb.port }}"
    - "{{ endpoints.ovnsb.port }}"
  tags: ufw

- name: set variable for database replication
  template: src=etc/default/ovn-central dest=/etc/default/ovn-central

- name: start ovn northd service
  service: name=ovn-central state=restarted enabled=yes

- include: monitoring.yml tags=monitoring,common
  when: monitoring.enabled|default('True')|bool
