---
horizon:
  keystone_api_version: 3
  session_timeout: 5400
  customize: false
  source:
    rev: 'kilo-bbg'
    python_dependencies:
      - { name: PyMySQL }
      - { name: python-memcached, version: '1.48' }
    system_dependencies:
      - apache2
      - libapache2-mod-wsgi
  logs:
    - paths:
        - /var/log/apache2/access.log
      fields:
        type: openstack
        tags: horizon
    - paths:
        - /var/log/apache2/error.log
      fields:
        type: openstack
        tags: horizon
    - paths:
        - /var/log/apache2/other_vhosts_access.log
      fields:
        type: openstack
        tags: horizon
  logging:
    debug: False
    verbose: True
