- name: Set br_provider facts
  set_fact:
    br_provider_addr: "{{ ansible_br_provider['ipv4']['address'] | default('') }}"
    br_provider_mask: "{{ ansible_br_provider['ipv4']['netmask'] | default('') }}"

- name: Set network_interfaces_d for softlayer compute nodes
  set_fact:
    network_interfaces_d:
      - filename: bond1.cfg
        contents: |
          auto bond1
          iface bond1 inet static
          #pre-up /sbin/ethtool -s bond1 speed 1000 duplex full autoneg on
          post-up ifenslave bond1 eth1 eth3
          pre-down ifenslave -d bond1 eth1 eth3
          bond-slaves none
          bond-mode 4
          bond-lacp-rate fast
          bond-miimon 100
          bond-downdelay 0
          bond-updelay 0
          bond-xmit_hash_policy 1

      - filename: br-provider.cfg
        contents: |
          allow-ovs br-provider
          iface br-provider inet static
          address {{ ansible_bond1['ipv4']['address'] | default(br_provider_addr) }}
          netmask {{ ansible_bond1['ipv4']['netmask'] | default(br_provider_mask) }}
          gateway {{ ansible_default_ipv4['gateway'] }}
