- name: Set ipv4 to bond1
  set_fact:
    softlayer_public_ipv4: "{{ ansible_bond1['ipv4'] }}"
  when: "'ipv4' in ansible_bond1"

- name: Set ipv4 to br-provider
  set_fact:
    softlayer_public_ipv4: "{{ ansible_br_provider['ipv4'] }}"
  when: "ansible_br_provider is defined and 'ipv4' in ansible_br_provider"

- name: Fail if neither supported condition is true
  fail: msg=No IP address on public bond or bridge
  when: softlayer_public_ipv4 is not defined

- name: Set network_interfaces_d for softlayer compute nodes
  set_fact:
    network_interfaces_d:
      - filename: bond1.cfg
        contents: |
          auto bond1
          iface bond1 inet static
          #pre-up /sbin/ethtool -s bond1 speed 1000 duplex full autoneg on
          post-up ifenslave bond1 eth1 eth3
          pre-down ifenslave -d bond1 eth1 eth3
          bond-slaves none
          bond-mode 4
          bond-lacp-rate fast
          bond-miimon 100
          bond-downdelay 0
          bond-updelay 0
          bond-xmit_hash_policy 1

      - filename: br-provider.cfg
        contents: |
          allow-ovs br-provider
          iface br-provider inet static
          address {{ softlayer_public_ipv4['address'] }}
          netmask {{ softlayer_public_ipv4['netmask'] }}
          gateway {{ ansible_default_ipv4['gateway'] }}
