- name: install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - openvswitch-switch
    - ovn-controller-vtep

- name: Install ovn-controller-vtep upstart script
  copy: src=ovn-controller-vtep.conf dest=/etc/init/ovn-controller-vtep.conf owner=root group=root mode=0644

- name: Install ovn-controller-vtep defaults
  template: src=ovn-controller-vtep.defaults dest=/etc/default/ovn-controller-vtep owner=root group=root mode=0644

- name: Install vtep-ovsdb upstart script
  copy: src=vtep-ovsdb.conf dest=/etc/init/vtep-ovsdb.conf owner=root group=root mode=0644

- name: Install vtep-ovsdb defaults
  template: src=vtep-ovsdb.defaults dest=/etc/default/vtep-ovsdb owner=root group=root mode=0644

- name: Install vtep-ovsdb ssl cert
  template: src=ovsclient-cert.pem dest=/etc/openvswitch/ovsclient-privkey.pem owner=root group=root mode=0600

- name: Install vtep-ovsdb ssl key
  template: src=ovsclient-privkey.pem dest=/etc/openvswitch/ovsclient-privkey.pem owner=root group=root mode=0600

- name: Install vtep-ovsdb ssl ca cert
  template: src=vswitchd.cacert dest=/etc/openvswitch/vswitchd.cacert owner=root group=root mode=0600

- name: Ensure service is running / enabled
  service: name=ovn-controller-vtep state=started enabled=yes
