---
keystone:
  enable_fatal_deprecations: False
  token_expiration_in_seconds: 86400
  admin_workers: 5
  public_workers: 5
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: PyMySQL }
      - { name: python-memcached }
    system_dependencies:
      - openssl
      - libldap2-dev
      - libsasl2-dev
      - libkrb5-dev
  alternatives:
    - keystone-manage
    - keystone-all
  jellyroll: False # custom middleware for password compliance
  logs:
    - paths:
      - /var/log/keystone/keystone-all.log
      fields:
        type: openstack
        tags: keystone,keystone-all
    - paths:
        - /var/log/keystone/keystone-manage.log
      fields:
        type: openstack
        tags: keystone,keystone-manage
  logging:
    debug: False
    verbose: True

  admin_project_domain_name: Default
  admin_project_name: admin
  domain_id_immutable: True
  domain_name_url_safe: strict
  prohibited_implied_role:
    - admin
  project_name_url_safe: strict
  secure_proxy_ssl_header: HTTP_X_FORWARDED_PROTO
  use_keystone_bootstrap: True

  identity_default_domain_id: default
  identity_mapping_backward_compatible_ids: True

  token_provider: fernet
  token_driver: sql
  revoke_driver: sql

  fernet_key_repository: /etc/keystone/fernet-keys/
  fernet_max_active_keys: 3

  deploy_method: uwsgi

  uwsgi:
    vassal:
      public:
        port: 5008
        processes: "{{ ansible_processor_vcpus }}"
        threads: "{{ ansible_processor_vcpus }}"
      admin:
        port: 5009
        processes: "{{ ansible_processor_vcpus }}"
        threads: "{{ ansible_processor_vcpus }}"
