---
- name: install ironic controller services
  upstart_service: name={{ item }}
                   user=ironic
                   cmd=/usr/local/bin/{{ item }}
                   config_dirs=/etc/ironic
  with_items:
    - ironic-api

- name: stop ironic services before db sync
  service: name={{ item }} state=stopped
  with_items:
    - ironic-api
  tags: db-migrate

# FIXME(deva)
# This dbsync is running only on certain hosts, when in actuality
# it might want to coordinate with all the ironic services
- name: sync ironic database
  command: ironic-dbsync
  when: database_create.changed or force_sync|default('false')|bool
  changed_when: true
  run_once: true
  notify: restart ironic services
  # we want this to always be changed so that it can notify the service restart
  tags: db-migrate

- name: start ironic controller services
  service: name={{ item }} state=started
  with_items:
    - ironic-api

# NOTE(deva)
# No need to open Ironic URL port in the firewall; it should only be available
# to internal networks
