- name: "get OpenStack Super repo"
  git: repo="{{ openstack_source.git_mirror }}/openstack"
       dest="/opt/stack"
       version="{{ ref }}"
       update="{{ openstack_source.git_update }}"
       recursive=yes
  register: git_result
  until: git_result|success
  retries: 3
  when: openstack_source.use_superproject
