---
- name: configure rsyslog
  template: src={{ item }} dest=/etc/rsyslog.d mode=0644
  with_fileglob: ../templates/etc/rsyslog.d/*
  notify: restart rsyslog

- name: configure logstash
  include: logging.yml
  when: logging.enabled|default(True)|bool
