---
- name: ifup provider network bridge
  command: ip link set dev {{item.split(':')[1]}} up
  with_items: "{{ neutron.bridge_mappings.split(',') }}"
  ignore_errors: yes

- name: restart ovn controller
  service: name=ovn-host state=restarted
