---
- name: ifup provider network bridge
  command: ip link set dev {{item.split(':')[1]}} up
  with_items: "{{ neutron.bridge_mappings.split(',') }}"
  ignore_errors: yes

- name: ifup provider network bridge with mapping
  command: ip link set dev {{ item }} up
  with_items: "{{ neutron.bridge_mapping.values() }}"

- name: restart openvswitch-switch
  service: name=openvswitch-switch state=restarted args="--save-flows=yes"

- name: restart ovn-host
  service: name=ovn-host state=restarted
