---
- include: resizeroot.yml

- name: set hostname
  hostname: name={{ hostname }}
  when: hostname is defined

- name: remove i386 architecture
  shell: dpkg --remove-architecture i386
  register: result
  changed_when: result.stderr == ''

# If this dir is missing then python apt.Cache().update() fails
- name: Create /var/lib/apt/lists dir
  file: dest=/var/lib/apt/lists state=directory owner=root group=root mode=755

- name: ubuntu apt source list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list
  when: openstack.ubuntu_mirror is defined
  notify:
    - update apt index

- meta: flush_handlers

- name: update apt index
  apt: update_cache=yes cache_valid_time=3600
  retries: 3
  delay: 30
  tags: ['prereboot']

- include: system-tools.yml

- include: python.yml
  tags: python

- include: ruby.yml
  tags: ruby

- name: set UTC timezone
  template: src=etc/timezone dest=/etc/timezone owner=root group=root mode=0644
  notify:
    - update timezone

- name: state path base directory
  file: dest={{ state_path_base }} state=directory

- include: ssl.yml tags=ssl

- include: ssh.yml

- include: networking.yml

- include: password-policy.yml

- include: system-file-permissions.yml

- include: ufw.yml
  tags: ufw

- include: ntp.yml
  tags: ntp

# Include serial console before kernel-tuning to build serial_console_cmdline
- include: serial-console.yml tty={{ common.serial_console }}
  tags: ['prereboot']

- include: ipmi.yml
  when: common.ipmi.enabled
  tags: ['prereboot']

- include: kernel-tuning.yml
  tags: ['prereboot']

- include: disable-swap.yml

- include: hwraid.yml
  when: common.hwraid.enabled
  tags: hwraid

- name: remove unwanted packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: common.packages_to_remove

- name: fetch Ursula revision
  local_action: command git describe --tags
  run_once: true
  sudo: no
  register: ursula_git_describe

- name: store Ursula revision
  set_fact: ursula_revision={{ ursula_git_describe.stdout }}

# run this last so we only update if run was successful
- name: drop an motd with ursula metadata
  template: src=etc/update-motd.d/90-ursula-motd dest=/etc/update-motd.d/90-ursula-motd mode=0755

- name: drop ursula release file
  template: src=etc/ursula-release dest=/etc/ursula-release mode=0640

- name: include stack name in /etc/issue
  lineinfile: dest=/etc/issue regexp="^{{ stack_env }} OpenStack Node" line="{{ stack_env }} OpenStack Node"

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool

- include: audit-logging.yml
  tags:
    - logrotate
    - logging
  when: logging.enabled|default('True')|bool
