- name: python dependencies
  apt: pkg={{ item }}
  with_items:
    - python2.7-dev
    - python-software-properties
    - cryptsetup
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev

- name: install additional python packages
  git: repo={{ item.repo }} dest=/opt/stack/{{ item.name }}
       version={{ item.rev }} accept_hostkey=True
  with_items: common.python_extra_packages

- name: install drivers
  command: python setup.py install chdir=/opt/stack/{{ item.name }}
  with_items: common.python_extra_packages

- name: install python modules
  pip: name={{ item }} state=latest
  with_items:
  - jinja2
  - 'requests[security]'

- name: install shade for ansible modules
  pip: name=shade version=0.16.0
