---
- name: get pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py
           dest=/tmp/get-pip.py

- name: install pip
  shell: python /tmp/get-pip.py

- name: update pip
  pip: name=pip state=latest
       extra_args='-i {{ openstack.pypi_mirror }}/+simple'
  when: openstack.pypi_mirror is defined and common.pip_version == 'latest'

- name: update pip
  pip: name=pip state=latest
       extra_args='-i https://pypi.python.org/simple/'
  when: openstack.pypi_mirror is undefined and common.pip_version == 'latest'

- name: update pip
  pip: name=pip version={{ common.pip_version }}
       extra_args='-i {{ openstack.pypi_mirror }}/+simple'
  when: openstack.pypi_mirror is defined and common.pip_version != 'latest'

- name: update pip
  pip: name=pip version={{ common.pip_version }}
       extra_args='-i https://pypi.python.org/simple/'
  when: openstack.pypi_mirror is undefined and common.pip_version != 'latest'

- name: root user pip config directory
  file: dest=/root/.pip state=directory

- name: pip config file
  template: src=etc/pip.conf dest=/root/.pip/pip.conf
  when: openstack.pypi_mirror is defined

- name: easyinstall config file
  template: src=etc/pydistutils.cfg dest=/root/.pydistutils.cfg
  when: openstack.easy_install_mirror is defined

- name: update pip
  pip: name=pip version={{ common.pip_version }}
       extra_args='-i {{ openstack.pypi_mirror }}/+simple'
  when: ansible_distribution_version == "12.04" and openstack.pypi_mirror is not defined

- name: install pip setuptools
  pip: name=setuptools state=latest

- name: cleanup system pip installs
  pip: name={{ item }} state=absent
  ignore_errors: yes
  with_items:
  - alembic
  - eventlet

- name: install additional python packages
  git: repo={{ item.repo }} dest=/opt/stack/{{ item.name }}
       version={{ item.rev }} accept_hostkey=True
  with_items: common.python_extra_packages

- name: install drivers
  command: python setup.py install chdir=/opt/stack/{{ item.name }}
  with_items: common.python_extra_packages

- name: install python modules
  pip: name={{ item }} state=latest
  with-items:
  - jinja2
  - setuptools
  - 'requests[security]'

- name: install shade for ansible modules
  pip: name=shade version=0.16.0
