- name: install resolvconf
  apt: pkg=resolvconf state=present

- name: resolv.conf file
  template:
    src: etc/resolvconf/resolv.conf.d/base.j2
    dest: /etc/resolvconf/resolv.conf.d/base
    owner: root
    group: root
    mode: 0644
  register: resolv_conf_base
  when: etc_resolv_conf is defined

- name: undo tail link to original to avoid duplicates
  file: path=/etc/resolvconf/resolv.conf.d/tail state=absent
  when: resolv_conf_base.changed

- name: update resolvconf
  when: resolv_conf_base.changed
  command: resolvconf -u
