---
dependencies:
  - role: nova-data
    nova:
      compute_driver: ironic.IronicDriver
      scheduler_host_manager: ironic_host_manager
      scheduler_default_filters: "{{ nova_ironic.scheduler_default_filters }}"
      ram_allocation_ratio: 1.0
      reserved_host_memory_mb: 0
      cpu_allocation_ratio: 1.0
    compute_ag: baremetal
