---
- name: install keystone service
  upstart_service:
    name: keystone
    user: keystone
    cmd: /usr/local/bin/keystone-all
    config_dirs: /etc/keystone

- name: stop keystone service before db sync
  service: name=keystone state=stopped
  when: database_create.changed or force_sync|default('false')|bool
  tags: db-migrate

- name: sync keystone database
  command: keystone-manage db_sync
  when: database_create.changed or force_sync|default('false')|bool
  run_once: true
  changed_when: true
  notify: restart keystone services
  # we want this to always be changed so that it can notify the service restart
  tags: db-migrate

- meta: flush_handlers

- name: start keystone
  service: name=keystone state=started
