---
- name: check if keystone user exists
  action: shell getent passwd keystone
  register: keystone_user
  failed_when: False
  changed_when: False

- name: keystone user
  user: name=keystone shell=/bin/false createhome=no
  when: keystone_user|success

- name: keystone user
  user: name=keystone comment=keystone shell=/bin/false system=yes
        home=/nonexistent createhome=no
  when: not keystone_user|success

- name: keystone config dir
  file: dest=/etc/keystone state=directory

- name: keystone log dir
  file: dest=/var/log/keystone state=directory mode=2750 owner=keystone
        group=adm

- name: Change keystone log dir acl
  acl: name=/var/log/keystone state=present default=yes etype={{ item.etype }} permissions={{ item.permission }}
  with_items:
    - etype: user
      permission: rw
    - etype: group
      permission: r
    - etype: other
      permission: r

- name: configure keystone
  template: src={{ item }} dest=/etc/keystone/
            mode={{ 0644 if 'policy.json' in item else 0640 }}
            owner=keystone group=keystone
  with_fileglob: ../templates/etc/keystone/*
  register: keystone_templates
  notify:
    - restart keystone services

- name: initialize fernet keys
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  args:
    creates: /etc/keystone/fernet-keys/*
  run_once: true
  delegate_to: "{{ groups['controller'][0] }}"
  tags: fernet-setup

- name: list fernet keys
  shell: ls /etc/keystone/fernet-keys | grep -E "^[0-9]+$"
  register: fernet_list
  failed_when: false
  changed_when: false

- name: Make rsync SSH keys
  shell: ssh-keygen -t rsa -b 2048 -q -f ~/.ssh/id_rsa
  args:
    creates: ~/.ssh/id_rsa

- name: Get SSH keys for distributing
  shell: cat ~/.ssh/id_rsa.pub
  register: fernet_sync_key
  changed_when: false

- name: Get host keys
  command: cat /etc/ssh/ssh_host_rsa_key.pub
  register: ssh_host_key
  changed_when: false

- name: Allow SSH as root using these keys
  authorized_key: user=root key="{{ hostvars[item]['fernet_sync_key'].stdout }}"
  with_items: groups["controller"]

- name: Add host keys to known hosts
  with_items: groups["controller"]
  known_hosts: path=/etc/ssh/ssh_known_hosts key="{{ item }} {{ hostvars[item]['ssh_host_key'].stdout }}" name="{{ item }}"

- name: Install python-mysqldb
  apt: name=python-mysqldb

- name: Install rsync
  apt: name=rsync

- name: sync keys to all other controllers
  synchronize:
    src: /etc/keystone/fernet-keys/
    dest: /etc/keystone/fernet-keys
  delegate_to: "{{ groups['controller'][0] }}"
  when: fernet_list.rc != 0 or fernet_list.stdout == ''

- include: eventlet.yml
  when: keystone.deploy_method == "eventlet"

- include: no-eventlet.yml
  when: keystone.deploy_method != "eventlet"

- include: uwsgi.yml
  when: keystone.deploy_method == "uwsgi"

- include: no-uwsgi.yml
  when: keystone.deploy_method != "uwsgi"

- name: permit access to keystone
  ufw: rule=allow to_port={{ item }} proto=tcp
  tags: ufw
  with_items:
    - "{{ endpoints.keystone.port.haproxy_api }}"
    - "{{ endpoints.keystone_admin.port.haproxy_api }}"
    - "{{ endpoints.keystone_legacy.port.haproxy_api }}"

- name: delete old token flush job
  file:
    path: /etc/cron.hourly/drop-expired-keystone-tokens
    state: absent

- include: monitoring.yml tags=monitoring,common
  when: monitoring.enabled|default('True')|bool

- include: logging.yml
  tags:
    - logrotate
    - logging
  when: logging.enabled|default('True')|bool
