- name: Assert Flavors
  os_nova_flavor:
    name={{item.name}}
    ram={{item.ram|omit}}
    vcpus={{item.vcpus|omit}}
    disk={{item.disk|omit}}
    ephemeral={{item.ephemeral|omit}}
    swap={{item.swap|omit}}
    rxtx_factor={{item.rxtx_factor|omit}}
    is_public={{item.is_public|omit}}
    flavorid={{item.flavorid|omit}}
  with_items: nova.flavors | default([])
