---
# NOTE: Glance does not know how to proxy copy-from URLs, so we should instead
# download the image files locally and create images using the file method.
- name: download images locally
  get_url: url={{ item.url }} dest=/tmp/{{ item.filename }}
  with_items: glance.images
- name: default images
  glance_image: name={{ item.name }}
                file=/tmp/{{ item.filename }}
                container_format=bare
                disk_format=qcow2
                auth_url={{ endpoints.auth_uri }}
                login_tenant_name=admin
                login_username=admin
                login_password={{ secrets.admin_password }}
                is_public=yes
                timeout=12000
  with_items: glance.images
  run_once: true
- name: remove local images
  file: path=/tmp/{{ item.filename }} state=absent
  with_items: glance.images
