---
dependencies:
  - role: endpoints
  - role: apt-repos
    repos:
        # TODO add OVS -master apt repository
      - repo: 'deb {{ apt_repos.ovn.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.ovn.key_url }}'
  - role: ovs-db
    ovs_db_dir: /var/lib/openvswitch
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
