---
heat:
  enable_fatal_deprecations: False
  enabled: True
  heartbeat_timeout_threshold: 30
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: PyMySQL }
      - { name: python-memcached }
    system_dependencies: []
  alternatives:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - heat-db-setup
    - heat-engine
    - heat-keystone-setup
    - heat-keystone-setup-domain
    - heat-manage
  logs:
    - paths:
        - /var/log/heat/heat-api.log
      fields:
        type: openstack
        tags: heat,heat-api
    - paths:
        - /var/log/heat/heat-engine.log
      fields:
        type: openstack
        tags: heat,heat-engine
    - paths:
        - /var/log/heat/heat-manage.log
      fields:
        type: openstack
        tags: heat,heat-manage
  logging:
    debug: False
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
  plugin_dirs: []
  engine_workers: 4
  stack_user_domain_name: heat
  domain_admin: heat_domain_admin
  stack_owner: heat_stack_owner
  stack_user: heat_stack_user
