---
dependencies:
  - role: keystone-defaults
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: keystone
    logdata: "{{ keystone.logs }}"
  - role: openstack-source
    project_name: keystone
    project_rev: "{{ keystone.source.rev }}"
    alternatives: "{{ keystone.alternatives }}"
    system_dependencies: "{{ keystone.source.system_dependencies }}"
    python_dependencies: "{{ keystone.source.python_dependencies }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: keystone
    alternatives: "{{ keystone.alternatives }}"
    when: openstack_install_method == 'package'
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
  - role: openstack-database
    database_name: keystone
  - role: uwsgi
    when: keystone.deploy_method == 'uwsgi'
    uwsgi_apt_plugins:
      - uwsgi-plugin-python
    uwsgi_vassals:
      - name: keystone-wsgi-admin
        state: present
        config:
          uid: keystone
          gid: keystone
          wsgi-file: "{{ openstack_source.virtualenv_base }}/keystone/bin/keystone-wsgi-admin"
          virtualenv: "{{ openstack_source.virtualenv_base }}/keystone"
          chdir: "{{ openstack_source.virtualenv_base }}/keystone"
          threads: "{{ keystone.uwsgi.vassal.admin.threads }}"
          processes: "{{ keystone.uwsgi.vassal.admin.processes }}"
          enable-threads: true
          plugin: python
          thunder-lock: true
          buffer-size: 65535
          socket: "127.0.0.1:{{ keystone.uwsgi.vassal.admin.port }}"
      - name: keystone-wsgi-public
        state: present
        config:
          uid: keystone
          gid: keystone
          wsgi-file: "{{ openstack_source.virtualenv_base }}/keystone/bin/keystone-wsgi-public"
          virtualenv: "{{ openstack_source.virtualenv_base }}/keystone"
          chdir: "{{ openstack_source.virtualenv_base }}/keystone"
          threads: "{{ keystone.uwsgi.vassal.public.threads }}"
          processes: "{{ keystone.uwsgi.vassal.public.processes }}"
          enable-threads: true
          plugin: python
          thunder-lock: true
          buffer-size: 65535
          socket: "127.0.0.1:{{ keystone.uwsgi.vassal.public.port }}"
