---
- name: permit swift proxy from anywhere
  ufw: rule=allow to_port=8090 proto=tcp
  tags: ufw

- name: swift-proxy service script
  template: src=roles/swift-common/templates/etc/init/swift-service.conf
            dest=/etc/init/swift-{{ item.service_name }}.conf mode=0644
  with_items:
    - { service_name: proxy, conf: proxy-server }

- name: configure swift-proxy
  template: src=etc/swift/proxy-server.conf dest=/etc/swift/proxy-server.conf
            owner=swift group=swift mode=0640
  notify: restart swift-proxy service

- meta: flush_handlers

- name: start swift-proxy service
  service: name=swift-proxy state=started
