---
dependencies:
  - role: endpoints
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
  - role: apt-repos
    repos:
        # TODO add OVS -master apt repository
      - repo: 'deb {{ apt_repos.ovn.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.ovn.key_url }}'
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
