---
monitoring:
  client_name: ~
  checks:
    memory:
      warning: 3
      critical: 2
  graphite:
    cluster_prefix: "stats.bbc.{{ stack_env }}.openstack"
    host_prefix: "stats.bbc.{{ stack_env }}.{{ ansible_nodename|regex_replace('\\\\.*$', '') }}"
  rabbit:
    vhost: /sensu
    username: sensu
    password: sensu
  check_handler: pagerduty
  metrics_handler: graphite
