---
- name: root user pip config directory
  file: dest=/root/.pip state=directory

- name: pip config file
  template: src=etc/pip.conf dest=/root/.pip/pip.conf
  when: openstack.pypi_mirror is defined

- name: easyinstall config file
  template: src=etc/pydistutils.cfg dest=/root/.pydistutils.cfg
  when: openstack.easy_install_mirror is defined

- name: install pip setuptools
  pip: name=setuptools state=latest

- name: install additional python packages
  git: repo={{ item.repo }} dest=/opt/stack/{{ item.name }}
       version={{ item.rev }} accept_hostkey=True
  with_items: common.python_extra_packages

- name: install drivers
  command: python setup.py install chdir=/opt/stack/{{ item.name }}
  with_items: common.python_extra_packages

- name: install python modules
  pip: name={{ item }} state=latest
  with_items:
  - jinja2
  - setuptools
  - 'requests[security]'

- name: install shade for ansible modules
  pip: name=shade version=0.16.0
