---
- name: root user pip config directory
  file: dest=/root/.pip state=directory

- name: pip config file
  template: src=etc/pip.conf dest=/root/.pip/pip.conf
  when: openstack.pypi_mirror is defined

- name: easyinstall config file
  template: src=etc/pydistutils.cfg dest=/root/.pydistutils.cfg
  when: openstack.easy_install_mirror is defined

- name: install pip setuptools
  pip: name=setuptools state=latest

- name: install pip virtualenv
  pip: name=virtualenv state=latest
